src/Entity/Works.php
<?php

namespace App\Entity;

use App\Repository\WorksRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: WorksRepository::class)]
class Works
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $count_process = null;

    #[ORM\Column(nullable: true)]
    private ?int $nucleus = null;

    #[ORM\Column(nullable: true)]
    private ?int $memory = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCountProcess(): ?int
    {
        return $this->count_process;
    }

    public function setCountProcess(int $count_process): self
    {
        $this->count_process = $count_process;

        return $this;
    }

    public function getNucleus(): ?int
    {
        return $this->nucleus;
    }

    public function setNucleus(?int $nucleus): self
    {
        $this->nucleus = $nucleus;

        return $this;
    }

    public function getMemory(): ?int
    {
        
        return  $this->memory;
    }

    public function setMemory(?int $memory): self
    {
        $this->memory = $memory;

        return $this;
    }
}

src/Form/Type/WorksType.php
<?php
namespace App\Form\Type;



use App\Entity\Works;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\ResetType;


class WorksType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add( child: 'name', type: TextType::class);
        $builder->add( child: 'count_process', type: NumberType::class);
        $builder->add( child: 'nucleus', type: NumberType::class);
        $builder->add( child: 'memory', type: NumberType::class);
        $builder->add('save', SubmitType::class, ['label' => 'Сохранить']);
        $builder->add('reset', ResetType::class, ['label' => 'Отмена']);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Works::class,
        ]);
    }

}

src/Controller/WorksController.php
<?php

namespace App\Controller;

use App\Entity\Works;
use App\Entity\Processes;
use App\Form\Type\WorksType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class WorksController extends AbstractController 
{
    //Загрузка списка work машин
    public function index(ManagerRegistry $doctrine): Response
    {        
        $works = $doctrine->getRepository(persistentObject: Works::class)->findAll();
        return $this->render( 'Works/index.html.twig', ['works' => $works]);
    }

    public function remove(ManagerRegistry $doctrine, int $id)
    {
        $processes = $doctrine->getRepository(persistentObject: Processes::class)->findBy(['work' => $id]);
        if(empty($processes))
        {
            $work = $doctrine->getRepository(persistentObject: Works::class)->find($id);
            $doctrine->getManager()->remove($work);
            $doctrine->getManager()->flush();
            $this->addFlash('success', 'Машина удалена');
        }
        else
        {
            $this->addFlash('error', 'Машину удалить нельзя, так как в ней есть процессы');
        }

        return $this->redirectToRoute('index');
    }

    //Выбор машины из списка
    public function carpressed(ManagerRegistry $doctrine, int $id): Response
    {
        $processes = $doctrine->getRepository(persistentObject: Processes::class)->findBy(['work' => $id]);
        return $this->render('Processes/index.html.twig',[
            'processes' => $processes
        ]);
    }

    //Добавение work машины, создание формы
    public function add(Request $request, ManagerRegistry $doctrine): Response
    {
        $works = new Works();
        $form = $this->createForm(WorksType::class, $works, [
            'action' => $this->generateUrl('add'),
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $work = $form->getData();

            $entityManager = $doctrine->getManager();
            $entityManager->persist($work);
            $entityManager->flush();
            return $this->redirectToRoute('index');
        }
        return $this->renderForm('Works/add.html.twig', ['form' => $form]);
    }

}

templates/Works/add.html.twig
<div class="card-body">
    <button type="button" class="close text-danger" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="py-10 text-center" style="white-space: nowrap;">Форма добавления машины</h4>
    <div class="block-add-form">
    {{ form(form) }}
    </div>
</div>

templates/Works/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Index{% endblock %}

{% block body %}
<header>
    <div class="logo"><h1><a href="/">Balancer</a></h1></div>
</header>
<div class="buttons">
    <div class="container">
        <div class="row">
            <button id="btn-add-process" class="btn btn-secondary btn-lg btn-block">
                <span class="btn-text text-default">Добавить процесс</span>
            </button> 
        </div>
    </div>
    
    <div class="container">
        <div class="row">
            <button id="btn-add-work-car" class="btn btn-secondary btn-lg btn-block">
                <span class="btn-text text-default">Добавить машину</span>
            </button> 
        </div>
    </div>
</div>
<div style="position: fixed;">
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.flashes('error') %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
    {% endfor %}
</div>
<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название машины</th>
            <th scope="col">Кол-во процессора</th>
            <th scope="col">Кол-во ядер</th>
            <th scope="col">Кол-во памяти</th>
        </tr>
    </thead>
    <tbody>
    {% for work in works %}
        <tr>
                <th scope="row">{{work.id}}</th>
                <td style="width: 200px;"><a href="{{ path('carpressed', {'id' :work.id})}}">{{work.name}}</a></td>
                <td>{{work.countProcess}}</td>
                <td>{{work.nucleus}}</td>
                <td>{{work.memory}}</td>
                <td style="width: 200px;"><a href="{{ path('removeWork', {'id' :work.id})}}">удалить</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% include 'form_add.html.twig' %}
{% endblock %}